import type { SyntheticClaim } from '@/types/claim.types'

export const SYNTHETIC_CLAIMS: SyntheticClaim[] = [
  {
    id: 'claim-001',
    patientFirstName: 'Marcus',
    patientLastName: 'Williams',
    dateOfService: '2026-02-02',
    procedureCode: '99214',
    procedureDescription: 'Office Visit, Established Patient, Moderate Complexity',
    billedAmount: '$285.00',
    billedAmountNumeric: 285.00,
    payerName: 'UnitedHealthcare',
    tradingPartnerServiceId: 'UHC001',
    claimControlNumber: 'CLM-2026-001847',
    payerClaimNumber: 'UHC-PCN-001847',
    submittedDate: '2026-02-03',
    daysOutstanding: 12,
    timelyFilingLimit: 90,
    daysUntilFilingDeadline: 78,
    scenario: 'PROCESSING_ON_SCHEDULE',
    priority: 'ON_TRACK',
    ageCategory: 'CURRENT',
    claimContext: 'Routine follow-up for hypertension management. Clean claim submitted electronically. No modifiers, correct ICD-10 codes, NPI verified.',
    mockClaimScenario: 'PROCESSING_ON_SCHEDULE',
  },
  {
    id: 'claim-002',
    patientFirstName: 'Sofia',
    patientLastName: 'Hernandez',
    dateOfService: '2026-01-18',
    procedureCode: '93000',
    procedureDescription: 'Electrocardiogram with Interpretation',
    billedAmount: '$195.00',
    billedAmountNumeric: 195.00,
    payerName: 'Cigna',
    tradingPartnerServiceId: 'CIGNA001',
    claimControlNumber: 'CLM-2026-001204',
    payerClaimNumber: 'CIG-PCN-001204',
    submittedDate: '2026-01-19',
    daysOutstanding: 27,
    timelyFilingLimit: 90,
    daysUntilFilingDeadline: 63,
    scenario: 'PAYMENT_PENDING',
    priority: 'ON_TRACK',
    ageCategory: 'CURRENT',
    claimContext: 'ECG ordered for palpitations workup. Claim adjudicated, payment issued via ERA. EFT in transit.',
    mockClaimScenario: 'PAYMENT_PENDING',
  },
  {
    id: 'claim-003',
    patientFirstName: 'James',
    patientLastName: 'Okafor',
    dateOfService: '2026-01-28',
    procedureCode: '27447',
    procedureDescription: 'Total Knee Replacement',
    billedAmount: '$18,500.00',
    billedAmountNumeric: 18500.00,
    payerName: 'BlueCross BlueShield of Texas',
    tradingPartnerServiceId: 'BCBSTX001',
    claimControlNumber: 'CLM-2026-001516',
    payerClaimNumber: 'BCBS-PCN-001516',
    submittedDate: '2026-01-29',
    daysOutstanding: 22,
    timelyFilingLimit: 180,
    daysUntilFilingDeadline: 158,
    scenario: 'ADDITIONAL_INFO_REQUESTED',
    priority: 'ACTION_REQUIRED',
    ageCategory: 'CURRENT',
    claimContext: 'Total knee replacement. Payer has suspended claim pending receipt of operative report and anesthesia records. Request date: February 14, 2026. Response due within 10 business days.',
    mockClaimScenario: 'ADDITIONAL_INFO_REQUESTED',
  },
  {
    id: 'claim-004',
    patientFirstName: 'Patricia',
    patientLastName: 'Chen',
    dateOfService: '2026-01-15',
    procedureCode: '90837',
    procedureDescription: 'Individual Psychotherapy, 60 minutes',
    billedAmount: '$220.00',
    billedAmountNumeric: 220.00,
    payerName: 'Aetna',
    tradingPartnerServiceId: 'AETNA001',
    claimControlNumber: 'CLM-2026-000992',
    payerClaimNumber: 'AET-PCN-000992',
    submittedDate: '2026-01-16',
    daysOutstanding: 35,
    timelyFilingLimit: 180,
    daysUntilFilingDeadline: 145,
    scenario: 'DENIED_BILLING_ERROR',
    priority: 'ACTION_REQUIRED',
    ageCategory: 'CURRENT',
    claimContext: 'Individual psychotherapy session. Denied: CARC 4 — Procedure code inconsistent with modifier used (modifier was omitted). Correct modifier and resubmit within 90 days of denial date.',
    mockClaimScenario: 'DENIED_BILLING_ERROR',
  },
  {
    id: 'claim-005',
    patientFirstName: 'Robert',
    patientLastName: 'Yamamoto',
    dateOfService: '2026-01-12',
    procedureCode: '70553',
    procedureDescription: 'MRI Brain with and without Contrast',
    billedAmount: '$3,200.00',
    billedAmountNumeric: 3200.00,
    payerName: 'Humana',
    tradingPartnerServiceId: 'HUMANA001',
    claimControlNumber: 'CLM-2026-000889',
    payerClaimNumber: 'HUM-PCN-000889',
    submittedDate: '2026-01-13',
    daysOutstanding: 40,
    timelyFilingLimit: 180,
    daysUntilFilingDeadline: 140,
    scenario: 'DENIED_MEDICAL_NECESSITY',
    priority: 'ACTION_REQUIRED',
    ageCategory: 'CURRENT',
    claimContext: 'MRI Brain ordered for persistent headaches. Denied: CARC 50 — Not deemed medical necessity by payer. Appeal deadline: 60 days from denial date (February 2, 2026). Prepare appeal with clinical documentation of prior conservative treatment attempts.',
    mockClaimScenario: 'DENIED_MEDICAL_NECESSITY',
  },
  {
    id: 'claim-006',
    patientFirstName: 'Dorothy',
    patientLastName: 'Washington',
    dateOfService: '2025-11-10',
    procedureCode: '99232',
    procedureDescription: 'Subsequent Hospital Care, Moderate Complexity',
    billedAmount: '$425.00',
    billedAmountNumeric: 425.00,
    payerName: 'Cigna',
    tradingPartnerServiceId: 'CIGNA001',
    claimControlNumber: 'CLM-2025-009341',
    payerClaimNumber: 'CIG-PCN-009341',
    submittedDate: '2025-11-11',
    daysOutstanding: 82,
    timelyFilingLimit: 90,
    daysUntilFilingDeadline: 8,
    scenario: 'TIMELY_FILING_AT_RISK',
    priority: 'URGENT',
    ageCategory: 'CRITICAL',
    claimContext: 'Original claim rejected at clearinghouse for invalid NPI. Corrected and resubmitted February 2, 2026. Must be accepted by Cigna before February 18 or the claim is void. 8 DAYS REMAIN.',
    mockClaimScenario: 'TIMELY_FILING_AT_RISK',
  },
  {
    id: 'claim-007',
    patientFirstName: 'Linda',
    patientLastName: 'Patel',
    dateOfService: '2026-01-25',
    procedureCode: '99213',
    procedureDescription: 'Office Visit, Established Patient, Low-Moderate Complexity',
    billedAmount: '$165.00',
    billedAmountNumeric: 165.00,
    payerName: 'Medicare / BCBS Medigap',
    tradingPartnerServiceId: 'MEDICARE001',
    claimControlNumber: 'CLM-2026-001388',
    payerClaimNumber: 'MCR-PCN-001388',
    submittedDate: '2026-01-26',
    daysOutstanding: 15,
    timelyFilingLimit: 365,
    daysUntilFilingDeadline: 350,
    scenario: 'SECONDARY_PENDING',
    priority: 'MONITOR',
    ageCategory: 'CURRENT',
    claimContext: 'Medicare paid $98.00 with $28.00 patient copay. Medigap secondary submitted via crossover. Secondary processing: 21-30 days after Medicare finalizes.',
    mockClaimScenario: 'SECONDARY_PENDING',
  },
  {
    id: 'claim-008',
    patientFirstName: 'Kevin',
    patientLastName: "O'Brien",
    dateOfService: '2025-12-20',
    procedureCode: '43239',
    procedureDescription: 'Upper GI Endoscopy with Biopsy',
    billedAmount: '$2,850.00',
    billedAmountNumeric: 2850.00,
    payerName: 'UnitedHealthcare',
    tradingPartnerServiceId: 'UHC001',
    claimControlNumber: 'CLM-2025-010847',
    payerClaimNumber: 'UHC-PCN-010847',
    submittedDate: '2025-12-21',
    daysOutstanding: 55,
    timelyFilingLimit: 90,
    daysUntilFilingDeadline: 35,
    scenario: 'APPEAL_IN_PROGRESS',
    priority: 'MONITOR',
    ageCategory: 'AGING',
    claimContext: 'Originally denied January 8, 2026 for site of service mismatch. Appeal submitted February 6, 2026. UHC 30-day review period. No response expected before March 8, 2026.',
    mockClaimScenario: 'APPEAL_IN_PROGRESS',
  },
]
